# Generated by Django 4.1 on 2024-09-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0002_alter_pregunta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID de la Pregunta'),
        ),
    ]
